# General bot configuration
bot:
  discord_key: ""
  command_prefix: ["!"]
  admin_minimum_role: "" #The lowest role that can use higher administrative functions, specify the exact name.
  rank_channel_id: "" #The channel id for the rank management channel
  extensions: [
    "cogs.dice",
    "cogs.currency",
    "cogs.echo",
    "cogs.reactionranker" ]
  ranks:
    EmojiID: "RankID" #Adds a user to the specified rank when they add an emoji with a matching id in the channel specified by rank_channel_id

currency:
  api_key: ""