# General bot configuration
bot:
  discord_key: ""
  command_prefix: ["!"]
  admin_minimum_role: "" #The lowest role that can use higher administrative functions, specify the exact name.
  rank_channel_id: "" #The channel id for the rank management channel
  extensions: [
    "cogs.dice",
    "cogs.currency",
    "cogs.echo",
    "cogs.reactionranker" ]
  ranks:
    EmojiID: "RankID" #Adds a user to the specified rank when they add an emoji with a matching id in the channel specified by rank_channel_id

currency:
  api_key: ""

managedroles:
  000000000000000001: #This role can give any role under it
    - "000000000000000011" #Example role id
    - "000000000000000012" #Example role id
    - "000000000000000013" #Example role id
    - "000000000000000014" #Example role id
  000000000000000002: #This role can give any role under it
    - "000000000000000021" #Example role id
    - "000000000000000022" #Example role id
    - "000000000000000023" #Example role id
  000000000000000003: #This role can give any role under it
    - "000000000000000031" #Example role id